[build-system]
requires = ["oryn~=2.0"]
build-backend = "oryn"

[project]
name = "umac"
version = "2.0"
description = "Implementation of the UMAC algorithm defined by RFC 4418"
license = "EUPL-1.2"
readme = "readme.md"
requires-python = "~=3.11"

[project.urls]
Repository = "https://github.com/slietar/umac"

[tool.oryn]
abi = "abi3"
interpreter = "cp311"
include = ["src/*"]

[[tool.oryn.distributions]]
platform = "macosx_14_0_arm64"
overrides = { "src/umac.abi3.so" = "../zig-out/lib/libumac-aarch64-macos.dylib" }

[[tool.oryn.distributions]]
platform = "manylinux2014_x86_64"
overrides = { "src/umac.abi3.so" = "../zig-out/lib/libumac-x86_64-linux.so" }

[[tool.oryn.distributions]]
platform = "manylinux2014_aarch64"
overrides = { "src/umac.abi3.so" = "../zig-out/lib/libumac-aarch64-linux.so" }
